# This orkflow will deploy a product every time changes are pushed into main branch
name: Product changes
on:
  push:
    branches:
      - 'main'
    paths:
      - 'product/src/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "12.18.2"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Build everything
        run: |
          yarn build
          
      - name: Deploy product
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          folder: ./product/build
          branch: gh-pages
